# Generated by Django 2.2 on 2020-09-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MendeleyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mendeley_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=250)),
                ('mendeley_username', models.CharField(max_length=250)),
                ('mendeley_password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mendeley', models.CharField(max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('tags', models.CharField(max_length=512)),
                ('abstract', models.TextField(null=True)),
                ('categories', models.ManyToManyField(to='catpal.Category')),
            ],
        ),
    ]
