# Generated by Django 2.2 on 2020-09-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mendeleygroup',
            name='documents',
            field=models.ManyToManyField(to='catpal.Document'),
        ),
    ]
