# Generated by Django 3.0.7 on 2020-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='id_mendeley',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
