# Generated by Django 3.1.3 on 2021-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0002_auto_20210121_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mendeleygroup',
            name='mendeley_password',
            field=models.CharField(max_length=250),
        ),
    ]
