# Generated by Django 2.2 on 2020-09-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0002_mendeleygroup_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='mendeleygroup',
            name='access_level',
            field=models.CharField(choices=[('private', 'private'), ('invite_only', 'invite_only'), ('public', 'public')], default='private', max_length=20),
        ),
    ]
