# Generated by Django 2.2 on 2020-09-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0003_mendeleygroup_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='mendeleygroup',
            name='link',
            field=models.CharField(default='www.mendeley.com', max_length=250),
        ),
    ]
