# Generated by Django 3.1.3 on 2021-04-22 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0003_auto_20210121_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='classified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 14, 11, 25, 909643, tzinfo=utc)),
        ),
    ]
