# Generated by Django 2.2 on 2020-09-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0004_mendeleygroup_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='id_mendeley',
            new_name='mendeley_id',
        ),
    ]
