# Generated by Django 3.2.4 on 2021-06-24 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0004_auto_20210422_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 20, 12, 50, 379513, tzinfo=utc)),
        ),
    ]
