# Generated by Django 2.2 on 2020-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0005_auto_20200923_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='websites',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
