# Generated by Django 3.1.3 on 2021-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0003_auto_20210121_1121'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, to='catpal.MendeleyGroup'),
        ),
    ]
