# Generated by Django 3.1.3 on 2020-12-03 04:02

import catpal.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(default=catpal.utils.generate_hash, max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MendeleyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mendeley_username', models.CharField(max_length=250)),
                ('mendeley_password', models.CharField(max_length=250)),
                ('mendeley_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(default='www.mendeley.com', max_length=250)),
                ('access_level', models.CharField(choices=[('private', 'private'), ('invite_only', 'invite_only'), ('public', 'public')], default='private', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mendeley_id', models.CharField(max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('tags', models.CharField(max_length=512)),
                ('websites', models.CharField(default='', max_length=1024)),
                ('abstract', models.TextField(null=True)),
                ('categories', models.ManyToManyField(to='catpal.Category')),
                ('groups', models.ManyToManyField(to='catpal.MendeleyGroup')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catpal.mendeleygroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catpal.category'),
        ),
    ]
