# Generated by Django 3.1.3 on 2021-01-21 16:05

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mendeleygroup',
            name='mendeley_password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=250)),
        ),
    ]
