# Generated by Django 3.1.3 on 2021-04-19 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0004_auto_20210419_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.DateTimeField(blank=True, default=datetime.datetime),
        ),
    ]
