# Generated by Django 3.1.3 on 2021-04-22 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0005_auto_20210419_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
