# Generated by Django 3.1.3 on 2021-04-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0007_auto_20210422_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='year',
        ),
    ]
