# Generated by Django 3.1.3 on 2021-04-22 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0008_remove_document_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.DateTimeField(default=datetime.date(2021, 4, 22)),
        ),
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
