# Generated by Django 3.1.3 on 2021-04-22 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catpal', '0009_auto_20210422_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 14, 7, 21, 726643, tzinfo=utc)),
        ),
    ]
